name: Update Context7 Docs

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'context7.json'
  release:
    types: [published]
  workflow_dispatch:

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update Context7 Documentation
        id: context7
        uses: rennf93/upsert-context7@1.1
        with:
          operation: refresh

      - name: Show result
        run: |
          echo "Success: ${{ steps.context7.outputs.success }}"
          echo "Status: ${{ steps.context7.outputs.status-code }}"
          echo "Message: ${{ steps.context7.outputs.message }}"
